name: Release
on:
  push:
    tags: ['v*']
jobs:
  release:
    permissions: {contents: write, id-token: write, attestations: write}
    uses: mwfl/.github/.github/workflows/portable-release.yml@824b78e7b1e880348562bd581f514ec581ba2639
    with:
      runner: windows-2022
      configure-preset: vs2022-x64
      build-preset: vs2022-x64-release
      build-directory: build/vs2022-x64
      artifact-slug: sqlite-viewer
      release-title: MWFL SQLite Viewer
